### ISSUE TITLE
Create domain package with basic data structures.

### ISSUE THREAD

**Issue by andrei-shabanski** [alesdokshanin/aio-loadtest#6]

**Comment by andrei-shabanski** [comment]
```Dockerfile
COPY ./api/src /app
COPY ./common /app/common
```

```yml
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
```

```bash
$ cd aio-testload/
$ docker build -f ./api/Dockerfile .
```
